"""add cuit supplier

Revision ID: 20bc59459829
Revises: cec936f4c70f
Create Date: 2024-04-19 02:04:00.982356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bc59459829'
down_revision: Union[str, None] = 'cec936f4c70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('cuit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'cuit')
    # ### end Alembic commands ###
