"""add is_creator to user

Revision ID: 2f08e1d2ce10
Revises: 34dc97277db3
Create Date: 2024-04-22 09:37:30.083159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f08e1d2ce10"
down_revision: Union[str, None] = "34dc97277db3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_creator", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_creator")
    # ### end Alembic commands ###
