"""reverse fk on category to: products > category

Revision ID: 34dc97277db3
Revises: 838ffc65690f
Create Date: 2024-04-20 17:11:19.809944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34dc97277db3'
down_revision: Union[str, None] = '838ffc65690f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_product_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'product_id')
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.add_column('category', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('category_product_id_fkey', 'category', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
