"""refactor is_creator nullable:True

Revision ID: 3d9b93f12014
Revises: dad7f1a465c0
Create Date: 2024-04-23 22:03:37.195584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9b93f12014'
down_revision: Union[str, None] = 'dad7f1a465c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
