"""refactoring and fixin models

Revision ID: 4d73a729608e
Revises: 34dc97277db3
Create Date: 2024-04-23 22:36:40.378249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d73a729608e'
down_revision: Union[str, None] = '34dc97277db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('product', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('product', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('transaction', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('is_creator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_creator')
    op.alter_column('transaction', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction', 'transaction_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('product', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'expiration_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('product', 'purchase_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
