"""add_email_supplier

Revision ID: 9aed3bf32742
Revises: 9bf728a12f0e
Create Date: 2024-04-10 23:12:06.692221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9aed3bf32742"
down_revision: Union[str, None] = "9bf728a12f0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("product", "barcode")
    op.add_column("supplier", sa.Column("email", sa.String(), nullable=False))
    op.add_column("supplier", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier", "is_active")
    op.drop_column("supplier", "email")
    op.add_column(
        "product",
        sa.Column(
            "barcode", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "category", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
