"""add fk category > business

Revision ID: ec7178021723
Revises: 9aed3bf32742
Create Date: 2024-04-18 00:22:04.515004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7178021723'
down_revision: Union[str, None] = '9aed3bf32742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'business_id')
    # ### end Alembic commands ###
